### ISSUE TITLE
build jdk12 error

### ISSUE THREAD

**Issue by luyongshou** [ptribble/jdk-sunos-builder#1]
Compiling 64 files for jdk.jconsole
Compiling 1000 files for jdk.hotspot.agent
Compiling 5 files for jdk.jsobject
Compiling 8 files for jdk.unsupported.desktop
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
^@^@^@^@^@^@^@^@^@^@
^@"/var/tmp/java-build/ud/jdk12u-jdk-12.0.2+10/src/hotspot/os_cpu/solaris_sparc/os_solaris_sparc.cpp", line 300: Error: "," expected instead of "asm".
1 Error(s) detected.
gmake[3]: *** [lib/CompileJvm.gmk:174: /var/tmp/java-build/ud/jdk12u-jdk-12.0.2+10/build/solaris-sparcv9-server-release/hotspot/variant-server/libjvm/objs/os_solaris_sparc.o] Error 2
gmake[3]: *** Waiting for unfinished jobs....
gmake[2]: *** [make/Main.gmk:257: hotspot-server-libs] Error 2

**Comment by ptribble** [comment]
What environment is this? That version ought to work, unless you're using the Studio compilers (which don't work) or a gcc that's either too old or too new (gcc7 should be fine).

**Comment by luyongshou** [comment]
sorry， I use oracleDeveloperStudio  。 I change gcc-7 work well。

**Comment by luyongshou** [comment]
use gcc-7

**Comment by luyongshou** [comment]
use gcc-7 work well
