### ISSUE TITLE
jdk15 build error

### ISSUE THREAD

**Issue by luyongshou** [ptribble/jdk-sunos-builder#2]
I user $ ./dobuild -b jdk15u-jdk-15.0.10-ga 

My Server is T4-1 

but build error message:

====================================================
A new configuration has been successfully created in
/var/tmp/java-build/ud/jdk15u-jdk-15.0.10-ga/build/solaris-sparcv9-server-release
using configure arguments '--enable-unlimited-crypto --with-boot-jdk=/usr/jdk/instances/jdk14 --with-native-debug-symbols=none --with-toolchain-type=gcc --disable-dtrace --disable-warnings-as-errors --enable-deprecated-ports=yes --with-jobs=3'.

Configuration summary:
* Debug level:    release
* HS debug level: product
* JVM variants:   server
* JVM features:   server: 'cds compiler1 compiler2 epsilongc g1gc jfr jni-check jvmti management nmt parallelgc serialgc services vm-structs'
* OpenJDK target: OS: solaris, CPU architecture: sparc, address length: 64
* Version string: 15.0.10-internal+0-adhoc.louis.jdk15u-jdk-15.0.10-ga (15.0.10-internal)

Tools summary:
* Boot JDK:       openjdk version "14.0.2-internal" 2020-07-14 OpenJDK Runtime Environment (build 14.0.2-internal+0-adhoc.louis.jdk14u-jdk-14.0.2-12) OpenJDK 64-Bit Server VM (build 14.0.2-internal+0-adhoc.louis.jdk14u-jdk-14.0.2-12, mixed mode, sharing)  (at /usr/jdk/instances/jdk14)
* Toolchain:      gcc (GNU Compiler Collection)
* C Compiler:     Version 7.5.0 (at /usr/bin/gcc)
* C++ Compiler:   Version 7.5.0 (at /usr/bin/g++)

Build performance summary:
* Cores to use:   3
* Memory limit:   32768 MB

The following warnings were produced. Repeated here for convenience:
WARNING: The Solaris and SPARC ports are deprecated and may be removed in a future release.

Building target 'all' in configuration 'solaris-sparcv9-server-release'
Compiling 8 files for BUILD_TOOLS_LANGTOOLS
Warning: No SCM configuration present and no .src-rev
Compiling 1 files for BUILD_JFR_TOOLS
Creating hotspot/variant-server/tools/adlc/adlc from 13 file(s)
Compiling 2 files for BUILD_JVMTI_TOOLS
Parsing 2 properties into enum-like class for jdk.compiler
Compiling 19 properties into resource bundles for jdk.compiler
Compiling 10 properties into resource bundles for jdk.javadoc
Compiling 12 properties into resource bundles for jdk.jdeps
Compiling 7 properties into resource bundles for jdk.jshell
Compiling 127 files for BUILD_java.compiler.interim
Compiling 405 files for BUILD_jdk.compiler.interim
Compiling 218 files for BUILD_jdk.javadoc.interim
^@/var/tmp/java-build/ud/jdk15u-jdk-15.0.10-ga/build/solaris-sparcv9-server-release/hotspot/variant-server/support/adlc/all-ad-src.ad(0) Semantic Error: :File read error, no input read

gmake[3]: *** [gensrc/GensrcAdlc.gmk:177: /var/tmp/java-build/ud/jdk15u-jdk-15.0.10-ga/build/solaris-sparcv9-server-release/hotspot/variant-server/support/adlc/_adlc_run_exec.marker] Error 1
gmake[2]: *** [make/Main.gmk:252: hotspot-server-gensrc] Error 2
gmake[2]: *** Waiting for unfinished jobs....

**Comment by ptribble** [comment]
There isn't any support yet for SPARC after jdk 15+24 (which is when support was removed); one of the aims of this repo is to put that back, but it's only a few days old so will take time to create working patches.

**Comment by luyongshou** [comment]
thanks
